### ISSUE TITLE
Grohe Blue Home water filter wrong size

### ISSUE THREAD

**Issue by stefinuxha** [Flo-Schilli/homeassistant-grohe_sense#29]
First of all thanks for keeping the integration up-to-date, i am using yours as is the most up to date. 👍 

When I look into the entities, I just changed the filter and I see in HA as full as 1000L one.
<img width="316" alt="Screenshot 2024-10-22 alle 13 55 27" src="https://github.com/user-attachments/assets/62708aeb-d626-48ba-a087-cea16dab4802">
However, in my case I set on the App the S-Size, the one I am using, which has a total life of 600L, and in the app is showing a more correct usage % like 93%.

Is it possible to read which filter is installed from the integration? or to manually set it according to the installed filter?

**Comment by Flo-Schilli** [comment]
Hi @stefinuxha :wave: 

as I'm not having a Grohe Blue it's a little bit harder for me to debug this. But I found an older response from the Grohe Blue Professional (which should be quite similar from the measurements afaik).

So that is the data Grohe is returning for the measurement:

```json
{
    "cleaning_count": 2,
    "date_of_cleaning": "2024-06-30T21:13:21.000+02:00",
    "date_of_co2_replacement": "2024-07-16T23:11:18.000+02:00",
    "date_of_filter_replacement": "2024-06-30T21:41:22.000+02:00",
    "filter_change_count": 3,
    "max_idle_time": 10875,
    "open_close_cycles_carbonated": 2352,
    "open_close_cycles_still": 2480,
    "operating_time": 14828,
    "power_cut_count": 73,
    "pump_count": 2487,
    "pump_running_time": 350,
    "remaining_co2": 91,
    "remaining_filter": 99,
    "time_since_last_withdrawal": 58,
    "time_since_restart": 536887329,
    "timeoffset": 120,
    "timestamp": "2024-07-16T23:11:18.000+02:00",
    "water_running_time_carbonated": 493,
    "water_running_time_medium": 10,
    "water_running_time_still": 221,
    "remaining_filter_liters": 3158,
    "remaining_co2_liters": 241
}
```
and there are also some parameter:

```json
{
    "water_hardness": 0,
    "carbon_hardness": 15,
    "filter_type": 6,
    "variant": 4,
    "auto_flush_reminder_notif": true,
    "consumables_low_notif": true,
    "product_information_notif": true
}
```

But to be honest I was expecting the backend to return the correct measurements.

Can you send also a screenshot from within the app and what the app is showing and what should be correct and the values corresponding in HA (I guess there shouldn't be a big change to the one you already provided)

If you want you can also start a new discussion, as there are a few persons here having a Grohe Blue Home or Professional, so we can get their information as well :smile:

**Comment by rama1981** [comment]
Good morning,

i´m owner of a blue prof.
the percentage of the Filter comes from the api. 
In my case I have 68% on the app and 89% on the integration.
CO ist similar.
maybe there is a factor in app in case of the water and carbon hardness?

it was more interesting the sensor: remaining_filter_litres

for example the 
sensor.my_grohe_blue_pro_date_of_co2_replacement
sensor.max_idle_time
sensor.water_running_time_still.
are quite wrong, but in my opinion it comes from the api, and not from integration.

And if you look at the webapp of Grohe - it´s not quite a Program with good informations, for example, you just see the water you got, what you started by app.

Sorry for my english, I´m a little bit rusty 

So that some values are not quite right in the integrations was/is not a problem for me, because i just use it for the statistics of the CO2 - but now i have a 5kg Bottle, so i know one time a year there has to be a change, and for the filter each second year.

if anyone needs screenshots / api copies, please feel free to ask. 

Have a nice day.

here is my code of the /dashboard
```

{
    "locations": [
        {
            "id": 5613326,
            "name": "###",
            "type": 1,
            "role": "owner",
            "timezone": "Europe/Vienna",
            "water_cost": -1,
            "energy_cost": -1,
            "heating_type": -1,
            "currency": "EUR",
            "default_water_cost": 0.003337,
            "default_energy_cost": 0.004376,
            "default_heating_type": 2,
            "emergency_shutdown_enable": true,
            "address": {
                "street": "###",
                "city": "###",
                "zipcode": "###",
                "housenumber": "",
                "country": "###",
                "country_code": "###",
                "additionalInfo": "",
                "state": ""
            },
            "rooms": [
                {
                    "id": ###,
                    "name": "Küche",
                    "type": 1,
                    "room_type": 15,
                    "role": "owner",
                    "appliances": [
                        {
                            "appliance_id": "###",
                            "installation_date": "2022-07-16T14:47:22.000+02:00",
                            "name": "My GROHE Blue Pro",
                            "serial_number": "###",
                            "type": 105,
                            "version": "01.04.Z10.0300.0104",
                            "tdt": "2024-10-23T00:16:31.000+02:00",
                            "timezone": 120,
                            "config": {
                                "co2_type": 2,
                                "co2_consumption_medium": 48,
                                "co2_consumption_carbonated": 65,
                                "guest_mode_active": false,
                                "auto_flush_active": false,
                                "flush_confirmed": false,
                                "hose_length": 270,
                                "f_parameter": 1,
                                "l_parameter": 3,
                                "flow_rate_still": 19,
                                "flow_rate_medium": 34,
                                "flow_rate_carbonated": 17
                            },
                            "role": "owner",
                            "registration_complete": true,
                            "presharedkey": "###",
                            "params": {
                                "water_hardness": 0,
                                "carbon_hardness": 15,
                                "filter_type": 6,
                                "variant": 4,
                                "auto_flush_reminder_notif": true,
                                "consumables_low_notif": true,
                                "product_information_notif": true
                            },
                            "error": {
                                "errors_1": false,
                                "errors_2": false,
                                "errors_3": false,
                                "errors_4": false,
                                "errors_5": false,
                                "errors_6": false,
                                "errors_7": false,
                                "errors_8": false,
                                "errors_9": false,
                                "errors_10": false,
                                "errors_11": false,
                                "errors_12": false,
                                "errors_13": false,
                                "errors_14": false,
                                "errors_15": false,
                                "errors_16": false,
                                "error1_counter": 2,
                                "error2_counter": 1,
                                "error3_counter": 17,
                                "error4_counter": 0,
                                "error5_counter": 0,
                                "error6_counter": 0,
                                "error7_counter": 0,
                                "error8_counter": 0,
                                "error9_counter": 0,
                                "error10_counter": 0,
                                "error11_counter": 0,
                                "error12_counter": 39,
                                "error13_counter": 0,
                                "error14_counter": 0,
                                "error15_counter": 0,
                                "error16_counter": 0
                            },
                            "state": {
                                "start_time": 1729659992,
                                "APPLIANCE_SUCCESSFUL_CONFIGURED": false,
                                "co2_empty": false,
                                "co2_20l_reached": false,
                                "filter_empty": false,
                                "filter_20l_reached": false,
                                "cleaning_mode_active": false,
                                "cleaning_needed": false,
                                "flush_confirmation_required": false,
                                "System_error_bitfield": 0
                            },
                            "data_latest": {
                                "measurement": {
                                    "cleaning_count": 2,
                                    "date_of_cleaning": "2024-06-30T21:13:21.000+02:00",
                                    "date_of_co2_replacement": "2024-10-22T21:48:40.000+02:00",
                                    "date_of_filter_replacement": "2024-06-30T21:41:22.000+02:00",
                                    "filter_change_count": 3,
                                    "max_idle_time": 10941,
                                    "open_close_cycles_carbonated": 2860,
                                    "open_close_cycles_still": 3027,
                                    "operating_time": 17126,
                                    "power_cut_count": 78,
                                    "pump_count": 3046,
                                    "pump_running_time": 427,
                                    "remaining_co2": 14,
                                    "remaining_filter": 89,
                                    "time_since_last_withdrawal": 13,
                                    "time_since_restart": 536887329,
                                    "timeoffset": 120,
                                    "timestamp": "2024-10-22T21:48:40.000+02:00",
                                    "water_running_time_carbonated": 611,
                                    "water_running_time_medium": 11,
                                    "water_running_time_still": 273,
                                    "remaining_filter_liters": 2853,
                                    "remaining_co2_liters": 37
                                }
                            },
                            "notifications": [],
                            "status": [
                                {
                                    "type": "update_available",
                                    "value": 0
                                },
                                {
                                    "type": "connection",
                                    "value": 1
                                }
                            ]
                        }
                    ]
                }
            ],
            "emergency_contacts": []
        }
    ]
}
```
and my screenshot
![Image (2)](https://github.com/user-attachments/assets/8594cc88-3e1e-45b2-9465-94df4b604cca)

**Comment by Flo-Schilli** [comment]
Hi @rama1981,

I guess there is a different application for the Grohe Blue then for the Sense products, right?
I'm just curious if it's possible to find out what they are doing client side to get that calculations as the retrieved values should be the same as their app is getting 😊

**Comment by rama1981** [comment]
Yes, you are right.
The app is called water systems by grohe

https://apps.apple.com/at/app/grohe-watersystems/id1502247993

I habe a display as well at my grohe chiller and for example, the filter % is similar to the app. So there should be a calc of used water multiply factor of carboness and max rate of the chosen filtertype (maybe).

**Comment by rama1981** [comment]
allright, i tried to change the water carbon - and the effect was nothing, so maybe in case of which filter you choose the capacitiy starts:
https://wassersysteme.grohe.at/de-AT/grohe-blue-filter-l-size-nur-fuer-blue-professional-blue-pure-und-grohe-red-40412001
_Kapazität 2500 Liter bei 20° dKH_
in my case instead of 20° dKH just 15° dKH - so 3200 liter instead of 2500: 
![image](https://github.com/user-attachments/assets/8dcbc493-6ffa-499f-8ea1-70ea9383fd51)

but i don´t know now whats the % problem between app and api

**Comment by Flo-Schilli** [comment]
> @Flo-Schilli yes, you are right. The app is called water systems by grohe
> 
> https://apps.apple.com/at/app/grohe-watersystems/id1502247993
> 
> I have a display as well at my grohe chiller and for example, the filter % is similar to the app. So there should be a calc of used water multiply factor of carboness and max rate of the chosen filtertype (maybe). Or maybe the summary of calculated max water use for filter and remaining?!? With a second device we can find out it much better, or with both of my outputs. (Yesterday and the days we did the trial&error)
> 
> **the things down below are not necessary in this post, it was just an idea but I can get all the values from sensors.**
> 
> _@Flo-Schilli do you have the possibility to make an action @ homeassistant, that i can extract for example the dashboard with one click. so i could try to change for example Filter type, or water carbon hardness, and notice each new values for each case. for example there is a feature in another integration mypvaillant_ https://github.com/signalkraft/mypyllant-component#readme
> 
> ![image](https://private-user-images.githubusercontent.com/43728481/379592676-ff2c4eeb-028f-430e-9366-a96c69be7a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTgyNzYsIm5iZiI6MTcyOTc1Nzk3NiwicGF0aCI6Ii80MzcyODQ4MS8zNzk1OTI2NzYtZmYyYzRlZWItMDI4Zi00MzBlLTkzNjYtYTk2YzY5YmU3YTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzI0ZWM1MTQ0ZGZkMGNhODc1MWE0Y2Y3NzA5YWVkZjZkOTNkYTI1MDZlOTVjOGVhMjViMGQyYjM1MjliOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3jfLX0DQlemYmqReCqmGFwqjrT6p-DWWc496orBKprw)
> 
> _in the other case i always have to work with postman to fetch the data. just an idea. I have no idea how much work it is. or maybe with the debug function to write the whole dashboard in the protocols_

Hi @rama1981,

thanks for the very detailed information again 👍 
I'll just check that topic with the actions as it would also allow me to export some data for the Sense Guard which is - at the moment - not integrateable in HA (at least as far as I know). But this would give the oportunity to export it and visualize it later. So I'll definitely dive into that topic 😄

**Comment by Flo-Schilli** [comment]
> allright, i tried to change the water carbon - and the effect was nothing at the grohe watersystem app, so maybe in case of which filter you choose the capacitiy starts: https://wassersysteme.grohe.at/de-AT/grohe-blue-filter-l-size-nur-fuer-blue-professional-blue-pure-und-grohe-red-40412001 _Kapazität 2500 Liter bei 20° dKH_ in my case instead of 20° dKH just 15° dKH - so 3200 liter instead of 2500: ![image](https://private-user-images.githubusercontent.com/43728481/379651637-8dcbc493-6ffa-499f-8ea1-70ea9383fd51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTgyNzYsIm5iZiI6MTcyOTc1Nzk3NiwicGF0aCI6Ii80MzcyODQ4MS8zNzk2NTE2MzctOGRjYmM0OTMtNmZmYS00OTlmLThlYTEtNzBlYTkzODNmZDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTYyNmVkMzhmMTJkNGY4YjQ3ZDhjYmYwOWViMmU2NWEwOTQ5ZjkzNmJhYjdmMmRjZjhkZmIxYjhiNTZhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wcdPzDyFaZkja8QUTpQNJ1BJCmSl3y33ZXWyMz1D2TQ)
> 
> but on the api there was something happened. i changed in the app from 15° dKH to 10° dKH and that was the result. - you see when i swiitched back to 15 ![image](https://private-user-images.githubusercontent.com/43728481/379656198-294c2d86-d00b-460d-bd70-32a2dc856feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTgyNzYsIm5iZiI6MTcyOTc1Nzk3NiwicGF0aCI6Ii80MzcyODQ4MS8zNzk2NTYxOTgtMjk0YzJkODYtZDAwYi00NjBkLWJkNzAtMzJhMmRjODU2ZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYmViNDFlOWEyNDc1MDg1Y2ZiODBjNmUxYzI5MzdhYTI4ODdhODU5ODMwNmUwYTA0Y2EyODNhZmY3M2ZjMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1dW8rBZaqmvKLkvFihAqRAreM6xrtKi9L5EiCl_RiCs)

Also thanks for all this information 👍 
I guess all the changes should be immediately reflected by the corresponding API after you set them.
Do you think - until I have implemented the actions - it would be possible for you to do some changes to the configuration, check the App information what it should be and always get the dashboard information for that from the API. I guess - if we do have enough changing data with the information the App is showing for those settings - it should be possible to check for the data which is somehow relevant for the app calculation 😄

**Comment by rama1981** [comment]
oh my god, that´s brilliant. 
I´ll test the ratings and levels by drinking a lot of water the next days, and I´ll give you feedback. thank you

**Comment by Flo-Schilli** [comment]
But don't drink too much water 😉
Thanks for trying it out and your support in this 😊

In regards to the device_name: it should be like I wrote it in another issue here: https://github.com/Flo-Schilli/homeassistant-grohe_sense/issues/35#issuecomment-2521515768

I tried it yesterday and it's working like that. I also will try to have all the queries I'm doing for the integration, also having them as an action available.

**Comment by rama1981** [comment]
> In regards to the device_name: it should be like I wrote it in another issue here: [#35 (comment)](https://github.com/Flo-Schilli/homeassistant-grohe_sense/issues/35#issuecomment-2521515768)
sorry, didn´t see followed this issue.

so well, i try to change some value, specially - drink some water - and carbon hardness.. And the following values in combination with filter and CO2 are changing.


```
locations:
    rooms:
        appliances:
            params:
              f_parameter: 4
              l_parameter: 2
              carbon_hardness: 20
            data_latest:
              measurement:
                open_close_cycles_carbonated: 2902
                open_close_cycles_still: 3158
                remaining_co2: 9
                remaining_filter: 84
                time_since_last_withdrawal: 56
                water_running_time_carbonated: 617
                water_running_time_medium: 11
                water_running_time_still: 290
                remaining_filter_liters: 2107
                remaining_co2_liters: 25
```

here are for example 3 different timestamps:

                open_close_cycles_carbonated: 2860 / 2899 / 2902
                open_close_cycles_still: 3027 / 3153 /  3158
                remaining_co2: 14 / 10 / 9 
                remaining_filter: 89 / 88 / 84
                water_running_time_carbonated: 611 / 617 / 617
                water_running_time_medium: 11 / 11 / 11
                water_running_time_still: 273 / 290 / 290
                remaining_filter_liters: 2853 / 2810 / 2107
                remaining_co2_liters: 37 / 26 / 25


i try now to do some timestamps at App plus your charming action - service and pull all the values - you see at the bottom out of the api.

I´ll give a reply in the next maybe two weeks. 

```
locations:
    rooms:
        appliances:
            tdt: "2024-12-08T19:22:27.000+01:00"
            config:
              co2_type: 2
              hose_length: 270
              co2_consumption_medium: 48
              co2_consumption_carbonated: 65
              f_parameter: 4
              l_parameter: 2
              flow_rate_still: 19
              flow_rate_medium: 34
              flow_rate_carbonated: 17
            params:
              water_hardness: 0
              carbon_hardness: 20
              filter_type: 6
              variant: 4
            data_latest:
              measurement:
                timestamp: "2024-12-08T19:22:27.000+01:00"
                date_of_cleaning: "2024-06-30T21:13:21.000+02:00"
                date_of_co2_replacement: "2024-12-08T19:22:27.000+01:00"
                date_of_filter_replacement: "2024-06-30T21:41:22.000+02:00"
                open_close_cycles_carbonated: 2902
                open_close_cycles_still: 3158
                remaining_co2: 9
                remaining_filter: 84
                time_since_last_withdrawal: 56
                water_running_time_carbonated: 617
                water_running_time_medium: 11
                water_running_time_still: 290
                remaining_filter_liters: 2107
                remaining_co2_liters: 25

```
```
locations:
    rooms:
        appliances:
            tdt: "2024-12-08T19:57:23.000+01:00"
            config:
              co2_type: 2
              hose_length: 270
              co2_consumption_medium: 48
              co2_consumption_carbonated: 65
              f_parameter: 1
              l_parameter: 3
              flow_rate_still: 19
              flow_rate_medium: 34
              flow_rate_carbonated: 17
            params:
              water_hardness: 0
              carbon_hardness: 15
              filter_type: 6
              variant: 4
            data_latest:
              measurement:
                timestamp: "2024-12-08T19:22:27.000+01:00"
                date_of_cleaning: "2024-06-30T21:13:21.000+02:00"
                date_of_co2_replacement: "2024-12-08T19:22:27.000+01:00"
                date_of_filter_replacement: "2024-06-30T21:41:22.000+02:00"
                open_close_cycles_carbonated: 2902
                open_close_cycles_still: 3158
                remaining_co2: 9
                remaining_filter: 66
                time_since_last_withdrawal: 56
                water_running_time_carbonated: 617
                water_running_time_medium: 11
                water_running_time_still: 290
                remaining_filter_liters: 2107
                remaining_co2_liters: 25

```
